---
# PRIMO PLAY: Setup disco dedicato per Rancher su tutti i server
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    vg_name: "vg_rancher"
    lv_name: "lv_rancher"
    rancher_mount_point: "/var/lib/rancher"
    filesystem_type: "xfs"
    mount_options: "defaults,noatime"
  roles:
    - role: create_disk

# NUOVO PLAY: Aggiorna /etc/hosts su tutti i server
- hosts: all
  become: yes
  gather_facts: no
  vars:
    rancher_domain: "cornelio.app.iac-svil.almaviva.it"
  roles:
    - role: update_hosts_file

# SECONDO PLAY: Installazione Rancher su TUTTI i masters
- hosts: masters
  become: yes
  gather_facts: no
  vars:
    rancher_domain: "cornelio.app.iac-svil.almaviva.it"
    rancher_password: "DanielE9233???"  # <-- AGGIUNGI QUESTA LINEA
    helm_version: "v3.11.0"
    rancher_version: "2.11.2"
    # Variabili per i certificati
    fullchain_pem_file: "fullchain.pem"
    privkey_pem_file: "privkey.pem"
    cacerts_pem_file: "cacerts.pem"
    remote_cert_path: "/root"
  roles:
    - role: master1_install
    - role: master1_config
    - role: master1_kubectl
    - role: master1_helm_cert_manager_install

# TERZO PLAY: Creazione cluster RKE2 su TUTTI i masters
- hosts: masters
  become: yes
  gather_facts: no
  vars:
    rancher_domain: "cornelio.app.iac-svil.almaviva.it"
    rancher_password: "DanielE9233???"
    helm_version: "v3.11.0"
    rancher_version: "2.11.2"
    cluster_name: "lellobello"
    cluster_k8s_version: "v1.31.9+rke2r1"
    cluster_cni: "canal"
  roles:
    - role: master1_create_cluster

# QUARTO PLAY: Setup kubectl sui nuovi manager
- hosts: new_managers
  become: yes
  gather_facts: no
  vars:
    rancher_domain: "cornelio.app.iac-svil.almaviva.it"
    helm_version: "v3.11.0"
    rancher_version: "2.11.2"
  roles:
    - kubectl_setup
